spring:
  application:
    name: strim

  # ?????? ?? ??
  datasource:
    url: jdbc:mysql://10.10.10.7:53308/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Op93348211955&&
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA ? Hibernate ??
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        highlight_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: 10.10.10.7
      port: 6379
      password:

# ?? ?? ??
logging:
  level:
    org.hibernate.SQL: DEBUG

# ?? ? ?? ??
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  swagger-ui:
    enabled: true